### ISSUE TITLE
2 issues (1-critical and 1 basic)

### ISSUE THREAD

**Issue by omerKurkutlu** [kousheekc/Kinematics#1]
1)Basic Issue
 l1, l2 can be change as float value , it is very simple to correct

2)Critical Issue
Code work fine for position on 1st and 4th quadrant of coordinate system but **it is not given
corrent output for 2nd and 3rd quadrant of coordinates system**

**Comment by kousheekc** [comment]
Thank you so much for pointing this out. Will look into it

**Comment by kousheekc** [comment]
resolved the issue with the use of atan2 function
