### ISSUE TITLE
More Detail on the Parameters

### ISSUE THREAD

**Issue by windfreeze** [kousheekc/Kinematics#2]
Hi,

May I know the details of the 6 parameters of "add_joint_axis" and 16 parameters of "add_initial_end_effector_pose"?
Thanks!

**Comment by kousheekc** [comment]
The add_joint_axis method expects 6 parameters corresponding to the coefficients of the 6D screw axes of the joints in the kinematic chain. These parameters can be found by studying the mechanical structure of the robot. Briefly, the screw axes of a particular joint in the kinematic chain describe the constraint between the end effector pose and the base. Note that the screw axes can be defined in the base frame or the end-effector frame, but for this library make sure to use the screw axes expressed in the base frame (often referred to as the S-frame).

The add_initial_end_effector_pose expects 16 parameters corresponding to the 4x4 homogenous transformation matrix of the end effector frame when the joints are all set to zero.

You can use the following video which explains these parameters in more detail by means of an example: [The add_joint_axis method expects 6 parameters corresponding to the coefficients of the 6D screw axes of the joints in the kinematic chain. These parameters can be found by studying the mechanical structure of the robot. Briefly, the screw axes of a particular joint in the kinematic chain describe the constraint between the end effector pose and the base. Note that the screw axes can be defined in the base frame or the end-effector frame, but for this library make sure to use the screw axes expressed in the base frame (often referred to as the S-frame).

The add_initial_end_effector_pose expects 16 parameters corresponding to the 4x4 homogenous transformation matrix of the end effector frame when the joints are all set to zero.

You can use the following video which explains these parameters in more detail by means of an example: https://youtu.be/cKHsil0V6Qk](https://youtu.be/cKHsil0V6Qk)
