### ISSUE TITLE
Further clarifications about adding joints 

### ISSUE THREAD

**Issue by MALSADA** [kousheekc/Kinematics#3]
Hi,

Thank you for providing this library, I have been looking for a FK/IK solution in Arduino for such a long time!

Would you kindly clarify what do the parameters mean when adding a new joint please -> kinematics_object.add_joint_axis(**0, 0,  1,  4, 0,    0**);
Should these present joint position + orientation of each joint ?  

Thank you very much,

**Comment by kousheekc** [comment]
Hi,

The add_joint_axis method takes in a joint axis expressed as a screw axis in the base frame. A screw axis representation can be used to determine the relationship between the two consecutive links that the joint connects. 

The following video explains the process of determining the screw axis of the joints by means of an example: [https://www.youtube.com/watch?v=cKHsil0V6Qk](https://www.youtube.com/watch?v=cKHsil0V6Qk) Note that the screw axis needs to be expressed in the S frame for this library.

Let me know if you need any other clarifications.
