### ISSUE TITLE
output from kinematics that drive the servo/stepper motor

### ISSUE THREAD

**Issue by mink007** [kousheekc/Kinematics#6]
Hello,
 I like the explanation that you gave in the other issue(issue #1).
I am specifically looking for code that tells the servo to rotate based on the output from Kinematics library.
If you can shed some light on that will be great.

Thank you.

**Comment by kousheekc** [comment]
Hi, 
the servo control can be incorporated by simply mapping the joint angle output of the inverse kinematics to your servo angles. You will have to mostly use the servo library and the `servo.writeMicroseconds(value)` or `servo.write(angle)` commands. As you might be aware most servos range from 0 to 180 degrees, however the output of the kinematics library gives positive and negative values around 0. So you may need to map the output of the kinematics library and the servo angles in the following manner:

**output -> angle**
-90 -> 0
0 -> 90
90 ->180
